name: golangci-lint
on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  golangci:
    name: Lint Sourcecode
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:

      - name: Check out code
        uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
          args: --timeout 240s
